Домашняя работа 7
TatyanaV24/Swift-homework pull request #2
Opened 2020-11-05 17:43 UTC by TatyanaV24

Решенные задачи по теме 7

2020-11-06 10:54 UTC, ios-review requested changes
Работа с гит идеальна 🔥🔥🔥

Код полностью решает все поставленные задачи👍

Попробуете сделать его чуточку короче, реализовав модель данных?

2020-11-06 10:54 UTC, ios-review commented on HW7/HW7/BlueViewController.swift
> +}
Пустые контроллеры не нужны.
В сториборде можно оставить просто UIViewController и все будет хорошо работать.

2020-11-06 10:54 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +        (children[0] as? EmbedViewController)?.view.backgroundColor = UIColor.green
Обращаться по индексу не очень безопасно, так как такого элемента может не быть и приложение упадет.

Какие видите способы реализовать безопасно?

2020-11-06 10:54 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +        if let vc = segue.destination as? EmbedViewController, segue.identifier == "embedShow"{
code style: нет пробела между "embedShow" и {

2020-11-06 10:54 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +
code style: не нужный new line

2020-11-06 10:54 UTC, ios-review commented on HW7/HW7/NextTwoViewController.swift
> +        self.view.window!.rootViewController?.dismiss(animated: true, completion: nil)
просто:
`dismiss(animated: true)`

2020-11-06 10:54 UTC, ios-review commented on HW7/HW7/NextTwoViewController.swift
> +    }
Предлагаю попробовать реализовать задачи с помощью модели данных, которую использовать во всех контроллерах приложения.

Для всего приложения создать модель ColorPallete.

```
enum ColorPallete: Int {
    case red = 0
    case green
    // etc

    var rgb: UIColor {
        // return appropriate value
    }

    var selectedDescription: String {
        // return appropriate value
    }

    var name: String {
        // return appropriate value
    }
}
```
У каждой кнопки задать tag, значение которого соответствует нужному кейсу ColorPallete.
У любой вью есть свойство tag, с помощью которого можно идентифицировать эту вью.
https://developer.apple.com/documentation/uikit/uiview/1622493-tag
Задать свойство можно как в коде, так и в сториборде.
Задайте соответствие tag кнопки и raw value для перечисления ColorPallete.
Создавать с помощью rawValue инициализатора
`let color = ColorPallete(rawValue: sender.tag)`

Для любой @IBAction функции можно назначить сколь угодно много кнопок для обработки нажатия.
Количество кода можно уменьшить, если обмениваться с другими контроллерами (через делегат) объектом перечисления ColorPallete.
А внутри контроллеров уже использовать вычислимые свойства этой модели для получения нужного значения: цвета или текста вроде "Выбран зеленый".

Будет примерно так:
```
@IBAction func buttonPressed(_ sender: UIButton) {
    guard let color = ColorPallete(rawValue: sender.tag) else { return }
    delegate?.update(color)
    dismiss(animated: true) 
}
```

Данную @IBAction функцию назначить для всех кнопок на контроллере.
Так сделать для всех контроллеров приложения.

2020-11-10 12:39 UTC, TatyanaV24 commented on HW7/HW7/ItemThreeViewController.swift
> +        (children[0] as? EmbedViewController)?.view.backgroundColor = UIColor.green
Вот тут я другого варианта пока не могу найти. При решении нашла только такой вариант, буду признательна за подсказку.

2020-11-11 11:01 UTC, ios-review requested changes
В остальных контроллерах также нужно использовать ColorPallete + одну реализацию @IBAction функции.
В ней создавать ColorPallete по tag кнопки.
А затем использовать свойства ColorPallete для преобразования в текст или UIColor.

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/BlueViewController.swift
>  class BlueViewController: UIViewController {
Класс контроллера все еще существует.
Он не нужен, если нет никакой логики.
В сториборде в поле Class можно использовать просто UIViewController и там настраивать параметры view.

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/BlueViewController.swift
>  class BlueViewController: UIViewController {
<img width="1405" alt="Screenshot 2020-11-11 at 17 22 08" src="https://user-images.githubusercontent.com/62285448/98800114-87387e00-2442-11eb-8fef-374dd9ac9ac0.png">

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +        if let vc = segue.destination as? EmbedViewController, segue.identifier == "embedShow"{
?

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/NextTwoViewController.swift
> +    }
code-style: отсупы

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/NextTwoViewController.swift
> +    }
данный код компилируется с ошибкой

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/NextTwoViewController.swift
> +    }
Эти свойства нужны, чтобы преобразовывать конкретное значение ColorPallete в значение цвета или текста выбранного цвета.
```
    var rgb: UIColor { // красный, зеленый, синий
        switch self {
        case .red:
            return .red
        case .green:
            return .green
        case .blue:
            return .blue
        }
    }
```

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/ItemTwoViewController.swift
> +        changeLabel.text = "Выбран \(_text) цвет"
Например, здесь необходимо использовать свойство selectedDescription у ColorPallete.

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/ItemTwoViewController.swift
> +        changeLabel.text = "Выбран \(_text) цвет"
Для этого необходимо реализовать это свойство.

2020-11-11 11:01 UTC, ios-review commented on HW7/HW7/ItemTwoViewController.swift
> +        changeLabel.text = "Выбран \(_text) цвет"
`changeLabel.text = colorPallete.selectedDescription`

2020-11-15 10:03 UTC, ios-review requested changes
Модель данных описывает все данные, с которыми работает приложение.
Но не все свойства обязательно должны использоваться в каждом контроллере.
Для контроллера могут использоваться только определенные свойства модели данных.

Попробуете применять рекомендации сразу ко всем аналогичным местам в коде сразу?

2020-11-15 10:03 UTC, ios-review commented on HW7/HW7/BlueViewController.swift
> -}
Пустые файлы также не нужны)
Ведь так?

2020-11-15 10:03 UTC, ios-review commented on HW7/HW7/EmbedViewController.swift
> +    }
Создать только 1 @IBAction функцию с параметром sender.
Назначить для кнопок tag.
Назначить в качестве обработчика события нажатия для всех кнопок одну функцию.
В реализации создавать ColorPallete по tag.
Преобразовывать конкретное значение ColorPallete в UIColor с помощью свойства rgb.

2020-11-15 10:03 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +        (children[0] as? EmbedViewController)?.view.backgroundColor = UIColor.green
В функции prepare(for segue: UIStoryboardSegue, sender: Any?) есть объект этого контроллера.
Его можно сохранить в свойство, а затем использовать здесь.
В этой строке получаете инстанс встраиваемого контроллера.
`if let vc = segue.destination as? EmbedViewController`

2020-11-15 10:03 UTC, ios-review commented on HW7/HW7/NextTwoViewController.swift
> +protocol NextDelegate {
code-style: 3 пустых строки, нужно не более одной.

2020-11-15 10:03 UTC, ios-review commented on HW7/HW7/RedViewController.swift
> +
Пустой файл.

2020-11-15 10:03 UTC, ios-review commented on HW7/HW7/ViewController.swift
> +enum ColorPallete: Int {
Для данной модели создать отдельный файл с именем ColorPallete и перенести в этот файл реализацию ColorPallete.

2020-11-16 12:23 UTC, ios-review requested changes
Задание было выполнено еще давно в соответствии с условиями!

Люблю добавлять свои "хотелки")
На скилбоксе задание приму.
Будет здорово, если все же доработаете его до конца.

2020-11-16 12:23 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +        }
Назначить кнопкам tag равные 1, 3 и 4.
Затем преобразовать tag в ColorPallete.
```
guard let color = ColorPallete(rawValue: sender.tag) else { return }
self.subView?.view.backgroundColor = color.rgb
```

2020-11-16 12:23 UTC, ios-review commented on HW7/HW7/ItemThreeViewController.swift
> +    @IBAction func transitionButton(_ sender: UIButton) {
Новую функцию необходимо переназначить в сториборде.
Сейчас приложение падает.

2020-11-16 12:23 UTC, ios-review commented on HW7/HW7/ColorPalleteViewController.swift
> +//  ColorPalleteViewController.swift
Просто ColorPallete.

2020-11-16 12:23 UTC, ios-review commented on HW7/HW7/BlueViewController.swift
> -
Рекомендую добавлять/изменять/удалять файлы проекта только с помощью Xcode.
Если удалить с помощью файловой системы, то изменения не будут отображены в файле проекта .xcodeproj, который содержит метаданные о проекте, в том числе исполняемые файлы.

Удалив с помощью файловое системы, файл проекта останется неизменным и будет считать, что файл до сих пор есть в проекте, хотя по факту его не будет.
Удалив с помощью Xcode, файл проекта также будет изменен.
Удалить с помощью Xcode можно, выделив файл, нажать на del.

2020-11-16 12:23 UTC, ios-review commented on HW7/HW7/EmbedViewController.swift
>      }
Новую функцию необходимо переназначить в сториборде.
Сейчас приложение падает.

2020-11-16 13:51 UTC, TatyanaV24 commented on HW7/HW7/BlueViewController.swift
> -
Удаление проводила именно по такой схеме, как Вы описали, возможно на git не все выгрузила..

2020-11-17 11:33 UTC, closed without merging