HW8
TatyanaV24/Swift-homework pull request #4
Opened 2020-11-18 17:00 UTC by TatyanaV24

2020-11-19 13:13 UTC, ios-review requested changes
В задании 1 есть критическая ошибка.
В задании 3 при изменении сегмента поведение не соответствует условию.

Также немного упростить алгоритмы + форматирование кода

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +            self.changeImageView.image = UIImage(named:catsImage[index])
Если нажимать вперед, а затем несколько раз назад, то приложение упадет с ошибкой:

> Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
> 2020-11-18 19:49:21.141941+0300 HW8[6220:446070] Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444"

Ошибка в вычислении индекса.
Если в массиве нет элемента с запрашиваемым индексом, то будет сообщение "Index out of range", что значит "Индекс вне диапазона".
Ошибка в вычислении индекса.
Индекс 0 всегда меньше, чем self.catsImage.count-1, а значит будет выполнен код после ":", то есть `self.index - 1`.
0 - 1 = -1
-1 не валидный индекс.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +
code-style: пустые строки.
В реальной разработке очень строго относятся к Code-style.

Все любят красивое оформление)

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +        case 0:
В данном случае такой подход не является оправданным, так как количество кода не уменьшается в любом случае, а код становится более запутанным.
У другого разработчика может возникнуть вопрос: почему выполнение код различается в зависимости от tag и что значит 0, а что значит 1.

Если же выделить две функции previous и next, то другой разработчик сразу поймет, что это обработчики нажатия кнопок, для которых должны происходить соотвествующие действия.
В случае previous уменьшение индекса и обновление картинки.
В случае next увеличение индекса и обновление картинки.

В предыдущем задании так делалось, так как код был одинаковый для любой функции. Отличалось только конкретное значение модели данных, связанное с кнопками при помощи tag.

Здесь же различие именно в логике, которое проще и нагляднее показать в виде двух функций-обработчиков.

Будет здорово, если попробуете смотреть на код со стороны и задавать вопрос: "Если бы я впервые видела данный код, я бы поняла его назначение сразу?"
Если возникает вопрос: "А что значит это значение и почему от него зависит логика?", то код в большинстве случае можно сделать более понятным.

Понятность для других - супер важный критерий при написании кода ПО.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +    let catsImage = [UIImage(named:"1"), UIImage(named:"2"),UIImage(named:"3"),UIImage(named:"4")]
Создать модель данных для картинки и подписи.

```
struct Cat {
    let icon: UIImage
    let name: String
}
```

Моделируйте!
Изменяемые данные группируйте по смыслу в сущности, в модели данных с помощью классов/структур/перечислений.

Композируйте простые данные в более сложные модели.
И декомпозируйте супер сложные объекты в более мелкие.

Сперва на сложном большом экране можно выделить простые повторяющиеся элементы.
В данном случае это в сумме картинка + текст.
Эти элементы располагаются сеткой 2х2.
Затем, выделив простые элементы, объединить их в модель.

Декомпозиция для выделения простых элементов -> композиция для выделения модели данных для сложного экрана.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +            }
Данный алгоритм можно упростить.

Если заметить, то разница для каждого элемента из массива только в frame.
Изменяется только frame для картинки+текста.
И то только x и y, а width и height постоянны.

Алгоритм в теле цикла может быть примерно такой:
1) Вычислить x и y в зависимости от index элемента.
2) Создать UIImageView с фиксированным frame.
3) Создать UILabel с фиксированным frame.
4) Создать UIView (эта вью будет контейнером для картинки и лейбла) с посчитанным x и y в пункте 1 и фиксированным width и height.
5) Добавить картинку+лейбл в вью из пункта 4.
6) Добавить вью из пункта 4 в иерархию вью для контроллера.

frame - это прямоугольник (левая верхняя вершина + размер), описывающий вью в системе координат супервью.
Так как картинка + лейбл будут добавляться в контейнер вью, то внутри нее для любой картинки и лейбла будут одинаковые frame.
То есть внутри системы координат этого контейнера frame для картинки и лейбла будут одинаковыми.

А вот frame каждого из этих четырех контейнеров в системе координат вью для контроллера будут отличаться, так как их нужно расположить сеткой 2х2.

Скрин может помочь:
<img width="444" alt="Screenshot 2020-11-19 at 19 58 56" src="https://user-images.githubusercontent.com/62285448/99669610-e4b37700-2aa1-11eb-9e0c-c27e0e772bef.png">

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +            }
В iOS используется перевернутая декартова система координат.
Начало в левом верхнем углу.
Ось X направлена вправо.
Ось Y направлена вниз.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +            }
Каждая вью образует свою систему координат.
Если в нее добавляется вью, то ее frame рассматривается именно в системе координат вью, в которую ее добавили.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +    }
code-style: отступы.

Без них принимать больше не буду.

Быстро отформатировать можно так:
- выделить все command+a
- отформатировать control+i

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +            dismiss(animated: true, completion: nil)
dismiss не нужен.
dismiss закрывает контроллер, если тот был показан модально.
В данном случае контроллер показан с помощью UITabBarController, поэтому этот вызов избыточен.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +    @objc func selectedValue(mySegmentControl: UISegmentedControl ) {
Данная функция может быть вызвана несколько раз, так как это обработчик события изменения сегмента.
Пользователь может сделать это очень много раз.

Получается так:
1) Пользователь нажал на сегмент.
2) Добавились вью из-за
```
            self.view.addSubview(textFieldOne)
             self.view.addSubview(textFieldTwo)
```
3) Пользователь нажал на сегмент.
4) Добавились вью из-за
```
            self.view.addSubview(textFieldOne)
             self.view.addSubview(textFieldTwo)
```
5) Пользователь нажал на сегмент.
6) Добавились вью из-за
```
            self.view.addSubview(textFieldOne)
             self.view.addSubview(textFieldTwo)
```
7) Пользователь нажал на сегмент.
8) Добавились вью из-за
```
            self.view.addSubview(textFieldOne)
             self.view.addSubview(textFieldTwo)
```

И так далее.

Создание и добавление вью необходимо производить один раз за все время жизни контроллера.
Функция viewDidLoad вызывается единожды за все время жизни контроллера.
Поэтому там будет ок создать и добавить все вьюхи.

По заданию требуется показывать/скрывать вьюхи.
Это можно сделать с помощью isHidden https://developer.apple.com/documentation/uikit/uiview/1622585-ishidden
В реализации `func selectedValue` необходимо только показывать/скрывать вью, соответствующие выбранному сегменту.

2020-11-19 13:13 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +    @objc func selectedValue(mySegmentControl: UISegmentedControl ) {
Про жизненный цикл контроллера по ссылке https://medium.com/good-morning-swift/ios-view-controller-life-cycle-2a0f02e74ff5

2020-11-19 16:20 UTC, TatyanaV24 commented on HW8/HW8/ViewController.swift
> +
Учту на будущее пунктик по оформлению. А есть какой-то особый список основных правил оформления кода или требования? Может где-то в документации указаны?

2020-11-19 18:26 UTC, TatyanaV24 commented on HW8/HW8/ViewController.swift
> +            self.changeImageView.image = UIImage(named:catsImage[index])
Переписала условия для вывода картинок, ошибок в индексе больше нет.

2020-11-19 18:27 UTC, TatyanaV24 commented on HW8/HW8/ViewController.swift
> +        case 0:
Тут все понятно, хотела уменьшить код, поэтому и объединила все в одно условие. Постараюсь думать не только о себе, но и возможных будущих коллегах.

2020-11-26 10:04 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +
Есть правила к проектированию API.
https://swift.org/documentation/api-design-guidelines/

Также есть более обширные правила, большая часть которых используется во множестве команд.
https://github.com/raywenderlich/swift-style-guide

2020-11-26 10:22 UTC, ios-review requested changes
Добавил подсказки)
Некоторые алгоритмы можно упростить.

По дополнительному заданию будем общаться в отдельном ПР.

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/BonusViewController.swift
> +class BonusViewController: UIViewController {
Вынести в отдельный ПР.

Для каждого ДЗ и для каждого дополнительного создавать отдельную ветку + отдельный ПР.

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/BonusViewController.swift
> +class BonusViewController: UIViewController {
И еще отдельный проект.

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +    let catsName = ["Funny cat","Cute cat", "Smile rabbit", "Happy cat"]
Модель создана, но не используется.

Сейчас два массива, которые по сути связаны логически.
Изменив один массив, можно забыть изменить другой, что при выполнении приложения может привести к падению приложения, так как в цикле элементы массива достаются по индексу.
А получение элемента по индексу небезопасно, так как может не быть элемента с заданным индексом в массиве.
И это критическая ошибка, приводящая к падению приложения.

Использование массива моделей будет безопасно.
`let cats = [Cat(), Cat(), Cat()]`
И после использовать этот один массив с полными данными.
```
for cat in cats {
    // остальной код
    // cat.icon
    // cat.name
}
```

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +        }
```
self.index = self.index == 0 ? self.catsImage.count - 1 : self.index - 1
self.changeImageView.image = UIImage(named:catsImage[index])
```

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +        }
упростить

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/ViewController.swift
> +class ViewController: UIViewController {
<img width="444" alt="Screenshot 2020-11-26 at 17 00 03" src="https://user-images.githubusercontent.com/62285448/100337742-5cd1ed80-300a-11eb-9588-6c29db22b435.png">

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +            self.view.addSubview(textFieldTwo)
Эти вью будут добавляться несколько раз.
Фактически будут удаляться и тут же сразу добавляться.
Это неэффективно.

Достаточно их все сразу добавить в иерархию в viewDidLoad, а здесь только показывать/скрывать с помощью isHidden.

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +            noButton.isHidden = true
Если каждую вью поместить в контейнер, а здесь показывать/скрывать этот контейнер, то кода будет меньше.

```
View:
    View1: textField1,2
    View2: image1,2
    View3: button1,2

view1.isHidden = false
view2.isHidden = true
view3.isHidden = true
```

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +        }
Алгоритм вычисления x и y можно еще упростить.
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        var x = 20
        var y = -250
        
        for (index, image) in images.enumerated() 
            if index % 2 == 0 {
                x = 20
                y += 270
            } else {
                x = 200
            }

            // остальной код
        }
    }
```

2020-11-26 10:22 UTC, ios-review commented on HW8/HW8/BonusViewController.swift
> +class BonusViewController: UIViewController {
Обсудим в отдельном ПР.

2020-11-28 13:52 UTC, TatyanaV24 commented on HW8/HW8/SegmentViewController.swift
> +            noButton.isHidden = true
Вот этот момент, логически понимаю, но реально не представляю, как реализовать. Пыталась осуществить через массив и словари. Но они не работают с isHidden.
Также была попытка провести реализацию через enum, но также все не то.
Помогите, пожалуйста, порцией подсказок)

2020-11-28 14:15 UTC, TatyanaV24 commented on HW8/HW8/BonusViewController.swift
> +class BonusViewController: UIViewController {
Я правильно понимаю, сокращение "ПР" - обозначает новый проект?
Получается у меня будет две параллельные ветки. В одной будет решение задач по основному ДЗ, во второй ветке будут допущены. задачи.

2020-11-29 10:36 UTC, ios-review commented on HW8/HW8/BonusViewController.swift
> +class BonusViewController: UIViewController {
ПР == пул реквест == pull request.
Для каждого задания, включая дополнительные, необходимо создавать отдельную ветку, отдельный проект, а после отдельный ПР.

> Получается у меня будет две параллельные ветки.

Веток может быть сколь угодно много.
Как пример, в моей работе в настоящий момент довольно много активных веток разработки, каждая из которых создана для каждой отдельной задачи.
Плюс каждый разработчик в команде также создает несколько отдельных веток для своих задач.

2020-11-29 10:48 UTC, ios-review requested changes
Приложение будет выполнять все условия задачи, если поправить задание 2 (таба Item2).

Будет круто, если также упростите немного код.

2020-11-29 10:48 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +            }
А зачем нужен второй вложенный цикл?

Координаты x и y вычисляются на каждом шаге цикла для определенного объекта модели Cat.
```
var x = 20
var y = -250
for (index, cat) in cats.enumerated() {
    // Код вычисления x и y для текущей модели cat.
    // Код создания вьюх для текущей модели cat.
}
```

2020-11-29 10:48 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +            }
С двумя циклами получается так, что x и y для всех cat будет равен нижней правой вью, что наглядно видно при запуске программы.
Все вью создаются справа внизу.

Результат выполнения всегда можно посмотреть в View Debugger.
На скрине показал, как его открыть.
<img width="1400" alt="Screenshot 2020-11-29 at 17 41 08" src="https://user-images.githubusercontent.com/62285448/100539607-41651d80-326a-11eb-8cf8-1f37a5606901.png">

2020-11-29 10:48 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +
👍

Теперь, чтобы упростить показ/скрытие, будет удобно добавить каждую пару в отдельную вью.
```
let view1 = UIView()
view1.addSubview(textFieldOne)
view1.addSubview(textFieldTwo)

let view2 = UIView()
view2.addSubview(buttonOne)
view2.addSubview(buttonTwo)

view.addSubview(view1)
view.addSubview(view2)
```

Далее создать свойство для каждой из этих вью контейнеров: view1, view2, view3.
И показывать/скрывать именно их.

Для свойства isHidden действует правило: если вью скрыта, то и все ее подвью также скрыты.

2020-11-29 10:48 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +class SegmentViewController: UIViewController {
<img width="1168" alt="Screenshot 2020-11-29 at 17 33 29" src="https://user-images.githubusercontent.com/62285448/100539696-cbad8180-326a-11eb-9c49-c8494fbd035b.png">

2020-12-01 09:54 UTC, ios-review approved these changes
Задание готово👍
Молодец🔥

Можно мержить.
Упростить в качестве дополнительного задания.

2020-12-01 09:54 UTC, ios-review commented on HW8/HW8/GalleryViewController.swift
> +            let elArr = image
кажется, что в создании новой константы нет смысла.
```
oneImage.image = image.icon
oneLabel.image = image.name
```

2020-12-01 09:54 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> +        view3.isHidden = true
👌

2020-12-01 09:54 UTC, ios-review commented on HW8/HW8/SegmentViewController.swift
> -            textFieldOne.isHidden = true
Более короткий алгоритм будет выглядеть так:
```
        for (index, view) in [view1, view2, view3].enumerated() {
            view.isHidden = index != mySegmentControl.selectedSegmentIndex
        }
```

А как можно сократить выбор цвета для view?

2020-12-01 14:51 UTC, TatyanaV24 commented on HW8/HW8/GalleryViewController.swift
> +            let elArr = image
Ой, это кусочек моих рассуждений, его не должно было быть.

2020-12-02 19:29 UTC, TatyanaV24 commented on HW8/HW8/SegmentViewController.swift
> -            textFieldOne.isHidden = true
Добавила в код следующий вариант:
view.backgroundColor = mySegmentControl.selectedSegmentIndex == 0 ? UIColor.green : (mySegmentControl.selectedSegmentIndex == 1) ? UIColor.blue :  UIColor.systemIndigo
Это самый краткий вариант, который смогла придумать. Поделитесь своим?

2020-12-02 19:38 UTC, merged