Частичное решение задание 10
TatyanaV24/Swift-homework pull request #8
Opened 2021-01-12 19:30 UTC by TatyanaV24

Дмитрий, добрый день.
Застопорилась на задаче с таблицей.
Я решила создавать строки, при помощи структур и классов.
А потом все объеденить в массив, как в уроке.
Думаю я вновь перемудрила.
Первоначальный вариант таблицы(до того что сейчас), создавал таблицу и разбивал на группы, но не удавалось добавить особенности строкам. Я смотрела видео-уроки, и читала как создавать разные строки в одной таблице и там использовали UITableViewController, а не UITableView.
Мне очень нужен Ваш дельный совет, т.к. не могу понять как разные строки свести в одну таблицу и как это прописать в коде.
По условию задачи у меня есть три вариант строк:
1. Картинка+лейбл+свитч
2.Картинка+лейбл+лейбл
3.Картинка+лейбл
Буду ждать Ваш ответ по этому вопросу.

2021-01-13 16:03 UTC, ios-review requested changes
Добавил подсказки по модели данных и ячейкам

2021-01-13 16:03 UTC, ios-review commented on HW10/HW10/Model/Model.swift
> +}
Использовать одну модель данных Setting и одну ячейку, которая может отрисовать любой вид Setting.

```
struct Setting {
    let title: String
    let icon: UIImage?
    let isSwitchHidden: Bool // здесь может быть название более точно описывающее назначение этого переключателя, но в к учебных целях ок)
    
    init(title: String, icon: UIImage?, isSwitchHidden: Bool = true)
}
```

2021-01-13 16:03 UTC, ios-review commented on HW10/HW10/NameTableViewCell.swift
> +}
Одна ячейка с разными состояниями подвью в зависимости от переданной модели данных.

2021-01-13 16:03 UTC, ios-review commented on HW10/HW10/TableViewController.swift
> +        cell.firstCell = cont[indexPath.row]
На этой строчке компилятор выдает ошибку.
Проект запустить нельзя.

2021-01-13 16:03 UTC, ios-review commented on HW10/HW10/TableViewController.swift
> +}
```
struct Setting {
}
struct SettingSection {
    let title: String
    let settings: [Setting]
}

class SettingsViewController: UIViewController {
    let settingSections = [SettingSection(title: "1", settings: [Setting()])]
}

```

2021-01-20 10:15 UTC, ios-review requested changes
SettingsViewController и TableViewController разные классы.
Проще выбрать что-то одно.
И работать именно с этим классом и его данными.

Оставьте SettingsViewController.
<img width="1404" alt="Screenshot 2021-01-20 at 17 12 35" src="https://user-images.githubusercontent.com/62285448/105160469-dd145b00-5b42-11eb-9f59-49970df72453.png">

2021-01-20 10:15 UTC, ios-review commented on HW10/HW10/SetTableViewCell.swift
> +    }
пустые методы не нужны

2021-01-20 10:15 UTC, ios-review commented on HW10/HW10/TableViewController.swift
>  }
удалить эти строки

2021-01-20 10:15 UTC, ios-review commented on HW10/HW10/TableViewController.swift
>  extension TableViewController: UITableViewDataSource, UITableViewDelegate {
extension SettingsViewController: ....

2021-01-20 10:15 UTC, ios-review commented on HW10/HW10/TableViewController.swift
> +        return cont.settingSections.count
return settingsSections.count

2021-01-22 14:05 UTC, TatyanaV24 commented on HW10/HW10/SetTableViewCell.swift
> +    }
это странно, но я не могу найти у себя в фале эти методы. Может так быть, что выгрузился какой-то старый вариант?

2021-01-24 09:16 UTC, ios-review commented
SettingsViewController и TableViewController разные классы.
Это причина ошибки при запуске приложения.

2021-01-26 11:37 UTC, ios-review requested changes
Комментарии + скрины
На скринах в консоли показаны ошибки layout.

<img width="1414" alt="Screenshot 2021-01-26 at 18 33 15" src="https://user-images.githubusercontent.com/62285448/105840195-32e67880-6005-11eb-8648-fa7df005d7c6.png">
<img width="1400" alt="Screenshot 2021-01-26 at 18 33 28" src="https://user-images.githubusercontent.com/62285448/105840241-45f94880-6005-11eb-958d-61764a20dbcb.png">
<img width="1401" alt="Screenshot 2021-01-26 at 18 33 46" src="https://user-images.githubusercontent.com/62285448/105840289-5dd0cc80-6005-11eb-8d83-94015fc15aba.png">

<img width="1402" alt="Screenshot 2021-01-26 at 18 30 43" src="https://user-images.githubusercontent.com/62285448/105840120-15b1aa00-6005-11eb-9fcb-49a30fd6877d.png">

2021-01-26 11:37 UTC, ios-review commented on HW10/HW10/TableViewController.swift
> +        }
В этом методе не должно быть зависимости на конкретные значения indexPath.
Вынести accessoryType в модель.

2021-01-26 11:37 UTC, ios-review commented on HW10/HW10/ScrollViewController.swift
> +    }
удалить и все будет отображаться

2021-02-04 12:08 UTC, ios-review requested changes
Задание выполнено в соответствии с требованиями👍

Попробуете доделать скрол вью в скрол вью?

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/Controller/ViewController.swift
> +    }
Зависимость размера ячейки от размеров экрана может сделать ячейку непропорциональной размерам коллекции, в случае если коллекция будет использоваться как часть большого экрана.

Рекомендую использовать зависимость от collectionView.bounds.

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/Controller/ViewController.swift
> +    var itemMenuArray:[Menu] = {
`let itemMenu`

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/Model/Model.swift
> +}
```
struct Menu {
    let imageName: String
}
```

Использование константных свойств делает код безопаснее, так как меньшее возможности для изменения значений.

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/TableViewController.swift
> +        }
в модели данных есть свойство accessoryType, но здесь не используется.
`cell.accessoryType = name.accessoryType`

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/TableViewController.swift
> +class TableViewController: UIViewController {
В сториборде где-то указан класс, которого на самом деле в проекте нет.
<img width="1394" alt="Screenshot 2021-02-04 at 18 51 42" src="https://user-images.githubusercontent.com/62285448/106889813-1c35d500-671b-11eb-8e12-a639138ed581.png">

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/SomeScrollViewController.swift
> +        imgScroll.addSubview(threeImage)
Скролл вью более сложная вью для реализации layout.
Если из кода, то необходимо еще задать content size.

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/SomeScrollViewController.swift
> +        imgScroll.addSubview(threeImage)
`imgScroll.contentSize = CGSize(width: 1000, height: imgScroll.bounds.size.height)`

2021-02-04 12:08 UTC, ios-review commented on HW10/HW10/SomeScrollViewController.swift
> +        imgScroll.addSubview(threeImage)
Но в этом случае нельзя использовать констрейнты.
Если используются констрейнты, то contentSize будет вычисляться по их правилам.

2021-02-13 09:02 UTC, ios-review approved these changes
Все задания работают в полном соответствии с условиями 🔥

Реквест можно мержить.

Прошу обратить внимание на комментарии.
В следующих реализациях необходимо их учитывать.

2021-02-13 09:02 UTC, ios-review commented on HW10/HW10/Controller/ViewController.swift
> +    var itemMenu:[Menu] = {
`let itemMenu: [Menu]`

По умолчанию используйте константы.
Они безопаснее, так как не позволят другому программисту изменить их значение, а значит всегда можно полагаться на их значение.
Другой программист может изменить константу на переменную, но в случае использования констант по умолчанию, он подумает несколько раз прежде чем изменит на переменную.

itemMenu нигде в коде дальше не меняется.

Такая запись самая короткая.
```
let itemMenu = [
    Menu(imageName: "1", price: "5 000 руб.", discount: "3 500 руб", name: "Котик Тимоха в желтой толстовке", percent: "- 30 %"),
    Menu(imageName: "2", price: "4 300 руб.", discount: "6 500 руб", name: "Котик-сплюшка в колпаке", percent: "- 35 %")
]
```

2021-02-13 09:02 UTC, ios-review commented on HW10/HW10/Model/Model.swift
> +    var imageName: String
Используйте константы!

2021-02-13 09:02 UTC, ios-review commented on HW10/HW10/Model/Model.swift
> +    var imageName: String
let по умолчанию

2021-02-13 09:02 UTC, ios-review commented on HW10/HW10/TableViewController.swift
>          }
Значение accessoryType необходимо использовать из модели для всех ячеек вне зависимости от значения index path.

2021-02-13 09:02 UTC, ios-review commented on HW10/HW10/TableViewController.swift
>          }
`cell.accessoryType = name.accessoryType` вместо строк 69-73

2021-02-13 19:08 UTC, merged